# Generated by Django 6.0.3 on 2026-03-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
