# Generated by Django 6.0.3 on 2026-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.CharField(db_index=True, default='default-room', max_length=100),
            preserve_default=False,
        ),
    ]
