# Generated by Django 6.0.3 on 2026-04-01 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatmessage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], db_index=True, default='shared', max_length=10),
        ),
    ]
