# Generated by Django 6.0.3 on 2026-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatmessage_chainlit_step_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source_type', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('cursor_field', models.CharField(blank=True, max_length=100, null=True)),
                ('cursor_value', models.CharField(blank=True, max_length=32, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='never', max_length=20)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
